<a href="https://colab.research.google.com/github/louduf/RECIPEKEEPER/blob/main/Introduction_to_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PANDAS DATAFRAMES

In [ ]:
import pandas as pd
data=pd.read_csv("/content/pima-indians-diabetes.csv")


In [ ]:
data.index

RangeIndex(start=0, stop=768, step=1)

# New section

In [ ]:
data.info

<bound method DataFrame.info of      Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]>

In [ ]:
data.head(5)

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
data.tail()

Pregnancies  Glucose  ...  Age  Outcome
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[5 rows x 9 columns]

In [ ]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
data.size

6912

In [ ]:
data.shape

(768, 9)

In [ ]:
data.memory_usage()

Index                        128
Pregnancies                 6144
Glucose                     6144
BloodPressure               6144
SkinThickness               6144
Insulin                     6144
BMI                         6144
DiabetesPedigreeFunction    6144
Age                         6144
Outcome                     6144
dtype: int64

In [ ]:
data.loc[:,'BloodPressure']

0      72
1      66
2      64
3      66
4      40
       ..
763    76
764    70
765    72
766    60
767    70
Name: BloodPressure, Length: 768, dtype: int64

In [ ]:
data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

### NUMPY

In [ ]:
import numpy as np

In [ ]:
x=np.array([2,3,4,5])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
print(x)

[2 3 4 5]


In [ ]:
y=np.array([4,5,'n',7])

In [ ]:
print(y)

['4' '5' 'n' '7']


In [ ]:
y= np.linspace(start=1,stop=5,num=5,endpoint= True, retstep= False)

In [ ]:
print(y)

[1. 2. 3. 4. 5.]


In [ ]:
y= np.linspace(start=1,stop=5,num=10,endpoint= True, retstep= False)

In [ ]:
y

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
y= np.linspace(start=1,stop=5,num=5,endpoint= True, retstep= True)

In [ ]:
y

(array([1., 2., 3., 4., 5.]), 1.0)

In [ ]:
z=np.arange(1,5,3)

In [ ]:
z

array([1, 4])

In [ ]:
z=np.arange(1,5,1)
z

array([1, 2, 3, 4])

In [ ]:
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.rand(2)

array([0.16550445, 0.07856884])